name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Скачать код
        uses: actions/checkout@v4

      - name: Установить Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Установить зависимости
        run: pip install pytest ruff

      - name: Линтер
        run: ruff check .

      - name: Форматирование
        run: ruff format --check .

      - name: Тесты
        run: python -m pytest -v